#
# Prettier Explosions
# Made with <3 by kixmc
#
# Some notes about the config:
# - Be mindful adjusting the visual cap, high values can really lag some players on lower end pcs. Values above 1000 may take a toll on server performance, depending on your rig
# - extra-visuals adds some additional visuals to explosions. Consider turning the option off when using increased visual caps to lessen fps lag
# - realistic-trajectories calculates an accurate trajectory for each exploded block (uses a bit more resources), when set to false a random trajectory (in limits) will be used instead. The realistic and non realistic explosions vary in appearance, so feel free to play around with both
# - Valid list-types are "whitelist" or "blacklist"
# - Set the world list to "world-list: []" to have an empty list. Empty list = prettier explosions everywhere

prettify:
  tnt-explosions: true
  bed-explosions: true
  creeper-explosions: true
  other-explosions: true

extra-visuals: true

realistic-trajectories: true

visual-cap-in-blocks: 185

list-type: whitelist
world-list:
  - "world"
  - "world_nether"
  - "world_the_end"